# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20160822_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.Project'),
        ),
    ]
