# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_auto_20160822_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date(2016, 8, 22)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2016, 8, 22)),
        ),
        migrations.AlterField(
            model_name='track',
            name='date',
            field=models.DateField(default=datetime.date(2016, 8, 22)),
        ),
    ]
