# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_auto_20160822_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 24, 17, 11, 30, 990335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 24, 17, 11, 31, 14397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='track',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 8, 24, 17, 11, 31, 15224, tzinfo=utc)),
        ),
    ]
