# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_auto_20160824_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
