# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_auto_20160824_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Zalążek'), ('IN PROGRESS', 'W opracowaniu'), ('DONE', 'Gotowy'), ('OLD', 'Staroć')], default='DRAFT', max_length=15),
        ),
    ]
