# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0012_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', {'css': 'label-warning', 'name': 'Zalążek'}), ('IN PROGRESS', {'css': 'label-info', 'name': 'W opracowaniu'}), ('DONE', {'css': 'label-success', 'name': 'Gotowy'}), ('OLD', {'css': 'label-default', 'name': 'Staroć'})], default='DRAFT', max_length=15),
        ),
    ]
