# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0015_auto_20160824_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', {'a': 'a', 'css': 'label-warning'}), ('IN PROGRESS', {'a': 'a', 'css': 'label-info'}), ('DONE', {'a': 'a', 'css': 'label-success'}), ('OLD', {'a': 'a', 'css': 'label-default'})], default='DRAFT', max_length=15),
        ),
    ]
